name: Publish
on:
  push:
    branches: [source]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        curl -LSfs https://raw.githubusercontent.com/crate-ci/gh-install/master/v1/install.sh | \
          sh -s -- \
          --git cobalt-org/cobalt.rs \
          --crate cobalt \
          --force \
          --target x86_64-unknown-linux-gnu \
          --tag v0.16.5
        echo COBALT_BIN=~/.cargo/bin/cobalt >> $GITHUB_ENV
    - name: Build
      run: ${{ env.COBALT_BIN }} build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: _site
